INSERT INTO province(name, code, created_at, updated_at) VALUES('Alberta', 'AB', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('British Columbia', 'BC', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Manitoba', 'MB', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('New Brunswick', 'NB', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Newfoundland and Labrador', 'NL', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Northwest Territories', 'NT', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Nova Scotia', 'NS', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Nunavut', 'NU', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Ontario', 'ON', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Prince Edward Island', 'PE', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Quebec', 'QC', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Saskatchewan', 'SK', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Yukon', 'YT', now(), now());

INSERT INTO province(name, code, created_at, updated_at) VALUES('Alabama','AL', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Alaska','AK', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Arizona','AZ', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Arkansas','AR', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('California','CA', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Colorado','CO', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Connecticut','CT', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Delaware','DE', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Florida','FL', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Georgia','GA', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Hawaii','HI', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Idaho','ID', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Illinois','IL', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Indiana','IN', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Iowa','IA', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Kansas','KS', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Kentucky','KY', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Louisiana','LA', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Maine','ME', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Maryland','MD', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Massachusetts','MA', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Michigan','MI', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Minnesota','MN', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Mississippi','MS', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Missouri','MO', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Montana','MT', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Nebraska','NE', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Nevada','NV', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('New Hampshire','NH', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('New Jersey','NJ', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('New Mexico','NM', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('New York','NY', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('North Carolina','NC', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('North Dakota','ND', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Ohio','OH', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Oklahoma','OK', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Oregon','OR', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Pennsylvania','PA', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Rhode Island','RI', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('South Carolina','SC', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('South Dakota','SD', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Tennessee','TN', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Texas','TX', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Utah','UT', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Vermont','VT', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Virginia','VA', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Washington','WA', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('West Virginia','WV', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Wisconsin','WI', now(), now());
INSERT INTO province(name, code, created_at, updated_at) VALUES('Wyoming','WY', now(), now());